### ISSUE TITLE
does opening urls or apps or exec comands work without code signed apps?

### ISSUE THREAD

**Issue by samueljohn** [norio-nomura/usernotification#2]
Hi,

if the usernotification is NOT code signed, does the Notification Center allow it to open urls on click?

**Comment by norio-nomura** [comment]
Hi,

If you want receive action from `NSUserNotificationCenter` on your app, you need implement `NSApplicationDelegate protocol` on your app.
`usernotification` does not implement any object adapting `NSApplicationDelegate protocol`.
So if `usernotification` is code signed or not, it can't handle action properly.

**Comment by samueljohn** [comment]
Thanks @norio-nomura for your quick answer. And if `usernotification` _would_ implement that call back function? Do you have any idea if it has to be code signed then or not?

I ask because, for `terminal-notifier`, I don't get any callbacks if I build it myself (and I don't have a cert from Apple).

**Comment by norio-nomura** [comment]
I have tested `terminal-notifier` without code sign.
It seems `terminal-notifier` received action and left below in console.log.

```
2013/06/04 22:54:58.230 terminal-notifier[8188]: User activated notification:
2013/06/04 22:54:58.230 terminal-notifier[8188]:  group ID: (null)
2013/06/04 22:54:58.231 terminal-notifier[8188]:     title: Terminal
2013/06/04 22:54:58.231 terminal-notifier[8188]:  subtitle: (null)
2013/06/04 22:54:58.231 terminal-notifier[8188]:   message: Execute: rake spec
2013/06/04 22:54:58.232 terminal-notifier[8188]: bundle ID: (null)
2013/06/04 22:54:58.232 terminal-notifier[8188]:   command: (null)
2013/06/04 22:54:58.232 terminal-notifier[8188]:      open: (null)
```

I have checked `terminal-notifier.app` does not have code sign as below.

```
% codesign -v /Users/norio/Library/Developer/Xcode/DerivedData/Terminal_Notifier-ftriicplrrgvixavztkfqckuqaxx/Build/Products/Debug/terminal-notifier.app                          ~
/Users/norio/Library/Developer/Xcode/DerivedData/Terminal_Notifier-ftriicplrrgvixavztkfqckuqaxx/Build/Products/Debug/terminal-notifier.app: code object is not signed at all
In architecture: x86_64
```

**Comment by samueljohn** [comment]
If you build `terminal-notifier` yourself, it has no code sign, I think. But if I download the pre-built app, it has got code sign (at this is what the developer is claiming).

So with your version that is not code-signed, Notification Center calls back to `terminal-notifier` but leaves "command" and "open" as `(null)`, even if you have set this for a notification like `terminal-notifier -message 'test' -open 'http://example.com'.

**Comment by samueljohn** [comment]
I am still trying to put all the information together :-)

**Comment by norio-nomura** [comment]
`terminal-notifier -message 'test' -open 'http://example.com'` shows notification, then clicking it cause opening browser and left below in console.log.

```
2013/06/05 9:47:14.822 terminal-notifier[11481]: User activated notification:
2013/06/05 9:47:14.822 terminal-notifier[11481]:  group ID: (null)
2013/06/05 9:47:14.823 terminal-notifier[11481]:     title: Terminal
2013/06/05 9:47:14.823 terminal-notifier[11481]:  subtitle: (null)
2013/06/05 9:47:14.823 terminal-notifier[11481]:   message: test
2013/06/05 9:47:14.824 terminal-notifier[11481]: bundle ID: (null)
2013/06/05 9:47:14.824 terminal-notifier[11481]:   command: (null)
2013/06/05 9:47:14.824 terminal-notifier[11481]:      open: http://example.com
```

**Comment by samueljohn** [comment]
And if you do the same with a self-compiled `terminal-notifier`?
I am asking, because I pulled in a request to add it to homebrew. So, if you have homebrew, would you mind to help me and `brew install terminal-notifier` ? Then issue:
`$(brew --prefix)/bin/terminal-notifier -message 'test' -open 'http://example.com'`

**Comment by samueljohn** [comment]
For me, no browser window open, so I thought, I might ask someone (you) who knows much more than me about Notification Center.

**Comment by norio-nomura** [comment]
I installed `terminal-notifier` by homebrew on my MacBook Air with OS X 10.8.4 Build 12E55.

```
% brew install terminal-notifier
==> Downloading https://github.com/alloy/terminal-notifier/archive/1.4.2.tar.gz
######################################################################## 100.0%
==> Patching
patching file 'Terminal Notifier.xcodeproj/project.pbxproj'
==> xcodebuild -project Terminal Notifier.xcodeproj -target terminal-notifier SYMROOT=build -verbose
==> Caveats
Homebrew built terminal-notifier, but without an developer certificate
from Apple, it will not be able to open URLs or execute commands when
the user clicks on a notification.
==> Summary
(here is beer mug emoji.)  /usr/local/Cellar/terminal-notifier/1.4.2: 11 files, 476K, built in 10 seconds
%
```

I run.

```
% /usr/local/bin/terminal-notifier -message 'test' -open 'http://example.com'
* Notification delivered.
%
```

I clicked notification, then browser window open.
console.log was

```
2013/06/06 12:37:06.347 terminal-notifier[18029]: User activated notification:
2013/06/06 12:37:06.347 terminal-notifier[18029]:  group ID: (null)
2013/06/06 12:37:06.348 terminal-notifier[18029]:     title: Terminal
2013/06/06 12:37:06.348 terminal-notifier[18029]:  subtitle: (null)
2013/06/06 12:37:06.348 terminal-notifier[18029]:   message: test
2013/06/06 12:37:06.349 terminal-notifier[18029]: bundle ID: (null)
2013/06/06 12:37:06.349 terminal-notifier[18029]:   command: (null)
2013/06/06 12:37:06.349 terminal-notifier[18029]:      open: http://example.com
```

I checked again it was not code signed. 

```
% codesign -vv /usr/local/Cellar/terminal-notifier/1.4.2/terminal-notifier.app
/usr/local/Cellar/terminal-notifier/1.4.2/terminal-notifier.app: code object is not signed at all
In architecture: x86_64
%
```

**Comment by samueljohn** [comment]
Wow thanks so much for your time. At some point I suck. After a reboot of my Mac it works for me too. (windows like... LOL). I guess because I had terminal-notifier before and Notification center was confused where to deliver, to the newly brewed one or the one I had before. Must be something like that.
You are the pro! Cool :thumbsup: 

I am going to remove the Caveat! Thanks again!
